development:
  adapter: postgresql
  encoding: unicode
  database: maxpoint2_development
  host: localhost
  pool: 5
  username: bnelson
  password: EDSW94edsw

test:
  adapter: postgresql
  encoding: unicode
  database: maxpoint2_test
  host: localhost
  pool: 5
  username: bnelson
  password: EDSW94edsw

staging:
  adapter: postgresql
  encoding: unicode
  database: d9shs2oho1rgn1
  host: ec2-54-204-2-217.compute-1.amazonaws.com
  port: 5432
  pool: 5
  username: ocvehxyuzszmwk
  password: LBXi3vGj3zsJpo38nGZJn_y6EN

production:
  adapter: postgresql
  encoding: unicode
  database: maxpoint2_production
  pool: 5
  username: bnelson
  password: EDSW94edsw
